version: '3'
services:
  rasa-core:
    image: fractal2k/personal-assistant:1.0
    ports:
      - 8080:5005
    depends_on:
      - rasa-actions

  rasa-actions:
    image: fractal2k/personal-assistant-actions:0.0
    expose:
      - "5055"
